services:
  app:
    build: .
    image: framepack:dev
    ports: 
      - "7880:7880"
    volumes:
      - ./hf_download:/hf_download
      - ./outputs:/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]